name: Update Activity API

on:
  push:
    paths:
      - "build_activity_json.py"
      - "sync_to_gitee.sh"
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: API
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/cache@v2
        name: Configure pip caching
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Python dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Update Activity JSON
        env:
          APP_TOKEN: ${{ secrets.APP_TOKEN }}
          APP_ID: ${{ secrets.APP_ID }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
        run: |-
          python build_activity_json.py
          cat activity.json
      - name: Install jq for Bash
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Update Gitee File
        env:
          GITEE_ACCESS_TOKEN: ${{ secrets.GITEE_ACCESS_TOKEN }}
        run: sh ./sync_to_gitee.sh
        shell: bash
      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email "curly230304@163.com"
          git config --global user.name "curly_bot"
          git pull
          git add -A
          git commit -m "Update activity.json" || exit 0
          git push
